services:
  opensearch-node:
    image: opensearchproject/opensearch:latest
    container_name: neuralsearch-prime-db

    environment:
      cluster.name: neuralsearch-cluster
      node.name: neuralsearch-node
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      OPENSEARCH_JAVA_OPTS: "-Xms2g -Xmx2g"
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      DISABLE_SECURITY_PLUGIN: "true"

    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

    deploy:
      resources:
        limits:
          memory: 4g

    ports:
      - "9200:9200"
      - "9600:9600"

    networks:
      - neuralsearch-net


  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: neuralsearch-dashboards

    environment:
      OPENSEARCH_HOSTS: '["http://opensearch-node:9200"]'
      DISABLE_SECURITY_PLUGIN: "true"

    deploy:
      resources:
        limits:
          memory: 512m

    ports:
      - "5601:5601"

    networks:
      - neuralsearch-net


networks:
  neuralsearch-net:
    driver: bridge
